=== scalar/scalar/packages/config/src/schemas/config.json
{
  "$ref": "#/definitions/ScalarConfig",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ConfigGuide": {
      "anyOf": [
        {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "folder": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": ["name", "folder"],
          "type": "object"
        },
        {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "sidebar": {
              "items": {
                "$ref": "#/definitions/ConfigSidebarItem"
              },
              "type": "array"
            }
          },
          "required": ["name", "sidebar"],
          "type": "object"
        }
      ]
    },
    "ConfigReference": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        }
      },
      "required": ["name", "path"],
      "type": "object"
    },
    "ConfigSidebarItem": {
      "anyOf": [
        {
          "additionalProperties": false,
          "properties": {
            "backgroundImage": {
              "type": "string"
            },
            "children": {
              "items": {
                "$ref": "#/definitions/ConfigSidebarItem"
              },
              "type": "array"
            },
            "description": {
              "type": "string"
            },
            "icon": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "path": {
              "type": "string"
            },
            "type": {
              "const": "page",
              "type": "string"
            }
          },
          "required": ["path", "type"],
          "type": "object"
        },
        {
          "additionalProperties": false,
          "properties": {
            "children": {
              "items": {
                "$ref": "#/definitions/ConfigSidebarItem"
              },
              "type": "array"
            },
            "icon": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "const": "folder",
              "type": "string"
            }
          },
          "required": ["name", "type", "children"],
          "type": "object"
        },
        {
          "additionalProperties": false,
          "properties": {
            "icon": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "const": "link",
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "required": ["name", "type", "url"],
          "type": "object"
        }
      ]
    },
    "ScalarConfig": {
      "additionalProperties": false,
      "description": "Top Level Scalar Config Object",
      "properties": {
        "customDomain": {
          "type": "string"
        },
        "guides": {
          "items": {
            "$ref": "#/definitions/ConfigGuide"
          },
          "type": "array"
        },
        "publishOnMerge": {
          "type": "boolean"
        },
        "references": {
          "items": {
            "$ref": "#/definitions/ConfigReference"
          },
          "type": "array"
        },
        "siteConfig": {
          "additionalProperties": false,
          "properties": {
            "bodyScript": {
              "type": "string"
            },
            "footer": {
              "type": "string"
            },
            "footerBelowSidebar": {
              "type": "boolean"
            },
            "footerCss": {
              "type": "string"
            },
            "headScript": {
              "type": "string"
            },
            "logo": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "additionalProperties": false,
                  "properties": {
                    "darkMode": {
                      "type": "string"
                    },
                    "lightMode": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              ]
            },
            "theme": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "siteMeta": {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "favicon": {
              "type": "string"
            },
            "ogImage": {
              "type": "string"
            },
            "title": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "subdomain": {
          "type": "string"
        }
      },
      "required": ["subdomain", "guides", "references"],
      "type": "object"
    }
  }
}

=== scalar/scalar/packages/config/test/valid.json
{
  "subdomain": "test.apidocumentation.com",
  "guides": [
    {
      "name": "First Guide",
      "sidebar": [
        {
          "path": "src/page-one.md",
          "type": "page",
          "name": "My First Page!!"
        },
        {
          "path": "src/page-two.md",
          "type": "page",
          "name": "Page title in the config!",
          "children": [
            {
              "name": "First Folder",
              "type": "folder",
              "children": [
                {
                  "url": "https://scalar.com/",
                  "type": "link",
                  "name": "Nested link"
                }
              ]
            }
          ]
        },
        {
          "path": "src/page-large.md",
          "type": "page",
          "children": [
            {
              "url": "https://scalar.com/",
              "type": "link",
              "name": "Nested link"
            }
          ]
        },
        {
          "path": "src/page-test.md",
          "type": "page",
          "name": "A weird test page!",
          "children": [
            {
              "path": "src/page-nested.md",
              "type": "page",
              "name": "Nested page"
            }
          ]
        }
      ]
    }
  ],
  "references": [],
  "siteConfig": {
    "footer": "<footer>\r\n  <p>This is the testing footer!!</p>\r\n</footer>",
    "theme": "some-theme"
  }
}
